# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('place_id', models.IntegerField()),
                ('user_likes', models.ManyToManyField(related_name='restaurant_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
