# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 01:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='user_dislikes',
            field=models.ManyToManyField(related_name='restaurant_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
