# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 03:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20170609_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ManyToManyField(related_name='dislikes', to='api.Restaurant')),
                ('user', models.ManyToManyField(related_name='disliker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
