# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 03:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='dislike',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='api.Restaurant'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='user',
        ),
        migrations.AddField(
            model_name='dislike',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disliker', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
